# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: RamensProto.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='RamensProto.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x11RamensProto.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xbd\x01\n\x06Ramens\x12\x11\n\tramenName\x18\x01 \x01(\t\x12\x0f\n\x07inrRate\x18\x02 \x01(\x01\x12\'\n\x08\x63omments\x18\x03 \x03(\x0b\x32\x15.Ramens.RamenComments\x1a\x66\n\rRamenComments\x12\x13\n\x0b\x63ommentFrom\x18\x01 \x01(\t\x12\x0f\n\x07\x63omment\x18\x02 \x01(\t\x12/\n\x0b\x63ommentTime\x18\x03 \x01(\x0b\x32\x1a.google.protobuf.Timestampb\x06proto3'
  ,
  dependencies=[google_dot_protobuf_dot_timestamp__pb2.DESCRIPTOR,])




_RAMENS_RAMENCOMMENTS = _descriptor.Descriptor(
  name='RamenComments',
  full_name='Ramens.RamenComments',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='commentFrom', full_name='Ramens.RamenComments.commentFrom', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='comment', full_name='Ramens.RamenComments.comment', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='commentTime', full_name='Ramens.RamenComments.commentTime', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=142,
  serialized_end=244,
)

_RAMENS = _descriptor.Descriptor(
  name='Ramens',
  full_name='Ramens',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='ramenName', full_name='Ramens.ramenName', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='inrRate', full_name='Ramens.inrRate', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='comments', full_name='Ramens.comments', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[_RAMENS_RAMENCOMMENTS, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=55,
  serialized_end=244,
)

_RAMENS_RAMENCOMMENTS.fields_by_name['commentTime'].message_type = google_dot_protobuf_dot_timestamp__pb2._TIMESTAMP
_RAMENS_RAMENCOMMENTS.containing_type = _RAMENS
_RAMENS.fields_by_name['comments'].message_type = _RAMENS_RAMENCOMMENTS
DESCRIPTOR.message_types_by_name['Ramens'] = _RAMENS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Ramens = _reflection.GeneratedProtocolMessageType('Ramens', (_message.Message,), {

  'RamenComments' : _reflection.GeneratedProtocolMessageType('RamenComments', (_message.Message,), {
    'DESCRIPTOR' : _RAMENS_RAMENCOMMENTS,
    '__module__' : 'RamensProto_pb2'
    # @@protoc_insertion_point(class_scope:Ramens.RamenComments)
    })
  ,
  'DESCRIPTOR' : _RAMENS,
  '__module__' : 'RamensProto_pb2'
  # @@protoc_insertion_point(class_scope:Ramens)
  })
_sym_db.RegisterMessage(Ramens)
_sym_db.RegisterMessage(Ramens.RamenComments)


# @@protoc_insertion_point(module_scope)
