# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: SimpleProto.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='SimpleProto.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x11SimpleProto.proto\"\x1b\n\x0bSimpleModel\x12\x0c\n\x04name\x18\x01 \x01(\tb\x06proto3'
)




_SIMPLEMODEL = _descriptor.Descriptor(
  name='SimpleModel',
  full_name='SimpleModel',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='SimpleModel.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=21,
  serialized_end=48,
)

DESCRIPTOR.message_types_by_name['SimpleModel'] = _SIMPLEMODEL
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

SimpleModel = _reflection.GeneratedProtocolMessageType('SimpleModel', (_message.Message,), {
  'DESCRIPTOR' : _SIMPLEMODEL,
  '__module__' : 'SimpleProto_pb2'
  # @@protoc_insertion_point(class_scope:SimpleModel)
  })
_sym_db.RegisterMessage(SimpleModel)


# @@protoc_insertion_point(module_scope)
