// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: RamensProto.proto
package scrib.hyde.models.protobufGen;

public final class RamensProto {
    private RamensProto() {
    }

    public static void registerAllExtensions(
            com.google.protobuf.ExtensionRegistryLite registry) {
    }

    public static void registerAllExtensions(
            com.google.protobuf.ExtensionRegistry registry) {
        registerAllExtensions(
                (com.google.protobuf.ExtensionRegistryLite) registry);
    }

    public interface RamensOrBuilder extends
            // @@protoc_insertion_point(interface_extends:Ramens)
            com.google.protobuf.MessageOrBuilder {

        /**
         * <code>string ramenName = 1;</code>
         *
         * @return The ramenName.
         */
        java.lang.String getRamenName();

        /**
         * <code>string ramenName = 1;</code>
         *
         * @return The bytes for ramenName.
         */
        com.google.protobuf.ByteString
        getRamenNameBytes();

        /**
         * <code>double inrRate = 2;</code>
         *
         * @return The inrRate.
         */
        double getInrRate();

        /**
         * <code>repeated .Ramens.RamenComments comments = 3;</code>
         */
        java.util.List<RamensProto.Ramens.RamenComments>
        getCommentsList();

        /**
         * <code>repeated .Ramens.RamenComments comments = 3;</code>
         */
        RamensProto.Ramens.RamenComments getComments(int index);

        /**
         * <code>repeated .Ramens.RamenComments comments = 3;</code>
         */
        int getCommentsCount();

        /**
         * <code>repeated .Ramens.RamenComments comments = 3;</code>
         */
        java.util.List<? extends RamensProto.Ramens.RamenCommentsOrBuilder>
        getCommentsOrBuilderList();

        /**
         * <code>repeated .Ramens.RamenComments comments = 3;</code>
         */
        RamensProto.Ramens.RamenCommentsOrBuilder getCommentsOrBuilder(
                int index);
    }

    /**
     * Protobuf type {@code Ramens}
     */
    public static final class Ramens extends
            com.google.protobuf.GeneratedMessageV3 implements
            // @@protoc_insertion_point(message_implements:Ramens)
            RamensOrBuilder {
        private static final long serialVersionUID = 0L;

        // Use Ramens.newBuilder() to construct.
        private Ramens(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
            super(builder);
        }

        private Ramens() {
            ramenName_ = "";
            comments_ = java.util.Collections.emptyList();
        }

        @java.lang.Override
        @SuppressWarnings({"unused"})
        protected java.lang.Object newInstance(
                UnusedPrivateParameter unused) {
            return new Ramens();
        }

        @java.lang.Override
        public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
            return this.unknownFields;
        }

        private Ramens(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            this();
            if (extensionRegistry == null) {
                throw new java.lang.NullPointerException();
            }
            int mutable_bitField0_ = 0;
            com.google.protobuf.UnknownFieldSet.Builder unknownFields =
                    com.google.protobuf.UnknownFieldSet.newBuilder();
            try {
                boolean done = false;
                while (!done) {
                    int tag = input.readTag();
                    switch (tag) {
                        case 0:
                            done = true;
                            break;
                        case 10: {
                            java.lang.String s = input.readStringRequireUtf8();

                            ramenName_ = s;
                            break;
                        }
                        case 17: {

                            inrRate_ = input.readDouble();
                            break;
                        }
                        case 26: {
                            if (!((mutable_bitField0_ & 0x00000001) != 0)) {
                                comments_ = new java.util.ArrayList<RamensProto.Ramens.RamenComments>();
                                mutable_bitField0_ |= 0x00000001;
                            }
                            comments_.add(
                                    input.readMessage(RamensProto.Ramens.RamenComments.parser(), extensionRegistry));
                            break;
                        }
                        default: {
                            if (!parseUnknownField(
                                    input, unknownFields, extensionRegistry, tag)) {
                                done = true;
                            }
                            break;
                        }
                    }
                }
            } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                throw e.setUnfinishedMessage(this);
            } catch (java.io.IOException e) {
                throw new com.google.protobuf.InvalidProtocolBufferException(
                        e).setUnfinishedMessage(this);
            } finally {
                if (((mutable_bitField0_ & 0x00000001) != 0)) {
                    comments_ = java.util.Collections.unmodifiableList(comments_);
                }
                this.unknownFields = unknownFields.build();
                makeExtensionsImmutable();
            }
        }

        public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
            return RamensProto.internal_static_Ramens_descriptor;
        }

        @java.lang.Override
        protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
            return RamensProto.internal_static_Ramens_fieldAccessorTable
                    .ensureFieldAccessorsInitialized(
                            RamensProto.Ramens.class, RamensProto.Ramens.Builder.class);
        }

        public interface RamenCommentsOrBuilder extends
                // @@protoc_insertion_point(interface_extends:Ramens.RamenComments)
                com.google.protobuf.MessageOrBuilder {

            /**
             * <code>string commentFrom = 1;</code>
             *
             * @return The commentFrom.
             */
            java.lang.String getCommentFrom();

            /**
             * <code>string commentFrom = 1;</code>
             *
             * @return The bytes for commentFrom.
             */
            com.google.protobuf.ByteString
            getCommentFromBytes();

            /**
             * <code>string comment = 2;</code>
             *
             * @return The comment.
             */
            java.lang.String getComment();

            /**
             * <code>string comment = 2;</code>
             *
             * @return The bytes for comment.
             */
            com.google.protobuf.ByteString
            getCommentBytes();

            /**
             * <code>.google.protobuf.Timestamp commentTime = 3;</code>
             *
             * @return Whether the commentTime field is set.
             */
            boolean hasCommentTime();

            /**
             * <code>.google.protobuf.Timestamp commentTime = 3;</code>
             *
             * @return The commentTime.
             */
            com.google.protobuf.Timestamp getCommentTime();

            /**
             * <code>.google.protobuf.Timestamp commentTime = 3;</code>
             */
            com.google.protobuf.TimestampOrBuilder getCommentTimeOrBuilder();
        }

        /**
         * Protobuf type {@code Ramens.RamenComments}
         */
        public static final class RamenComments extends
                com.google.protobuf.GeneratedMessageV3 implements
                // @@protoc_insertion_point(message_implements:Ramens.RamenComments)
                RamenCommentsOrBuilder {
            private static final long serialVersionUID = 0L;

            // Use RamenComments.newBuilder() to construct.
            private RamenComments(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
                super(builder);
            }

            private RamenComments() {
                commentFrom_ = "";
                comment_ = "";
            }

            @java.lang.Override
            @SuppressWarnings({"unused"})
            protected java.lang.Object newInstance(
                    UnusedPrivateParameter unused) {
                return new RamenComments();
            }

            @java.lang.Override
            public final com.google.protobuf.UnknownFieldSet
            getUnknownFields() {
                return this.unknownFields;
            }

            private RamenComments(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws com.google.protobuf.InvalidProtocolBufferException {
                this();
                if (extensionRegistry == null) {
                    throw new java.lang.NullPointerException();
                }
                com.google.protobuf.UnknownFieldSet.Builder unknownFields =
                        com.google.protobuf.UnknownFieldSet.newBuilder();
                try {
                    boolean done = false;
                    while (!done) {
                        int tag = input.readTag();
                        switch (tag) {
                            case 0:
                                done = true;
                                break;
                            case 10: {
                                java.lang.String s = input.readStringRequireUtf8();

                                commentFrom_ = s;
                                break;
                            }
                            case 18: {
                                java.lang.String s = input.readStringRequireUtf8();

                                comment_ = s;
                                break;
                            }
                            case 26: {
                                com.google.protobuf.Timestamp.Builder subBuilder = null;
                                if (commentTime_ != null) {
                                    subBuilder = commentTime_.toBuilder();
                                }
                                commentTime_ = input.readMessage(com.google.protobuf.Timestamp.parser(), extensionRegistry);
                                if (subBuilder != null) {
                                    subBuilder.mergeFrom(commentTime_);
                                    commentTime_ = subBuilder.buildPartial();
                                }

                                break;
                            }
                            default: {
                                if (!parseUnknownField(
                                        input, unknownFields, extensionRegistry, tag)) {
                                    done = true;
                                }
                                break;
                            }
                        }
                    }
                } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                    throw e.setUnfinishedMessage(this);
                } catch (java.io.IOException e) {
                    throw new com.google.protobuf.InvalidProtocolBufferException(
                            e).setUnfinishedMessage(this);
                } finally {
                    this.unknownFields = unknownFields.build();
                    makeExtensionsImmutable();
                }
            }

            public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
                return RamensProto.internal_static_Ramens_RamenComments_descriptor;
            }

            @java.lang.Override
            protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internalGetFieldAccessorTable() {
                return RamensProto.internal_static_Ramens_RamenComments_fieldAccessorTable
                        .ensureFieldAccessorsInitialized(
                                RamensProto.Ramens.RamenComments.class, RamensProto.Ramens.RamenComments.Builder.class);
            }

            public static final int COMMENTFROM_FIELD_NUMBER = 1;
            private volatile java.lang.Object commentFrom_;

            /**
             * <code>string commentFrom = 1;</code>
             *
             * @return The commentFrom.
             */
            @java.lang.Override
            public java.lang.String getCommentFrom() {
                java.lang.Object ref = commentFrom_;
                if (ref instanceof java.lang.String) {
                    return (java.lang.String) ref;
                } else {
                    com.google.protobuf.ByteString bs =
                            (com.google.protobuf.ByteString) ref;
                    java.lang.String s = bs.toStringUtf8();
                    commentFrom_ = s;
                    return s;
                }
            }

            /**
             * <code>string commentFrom = 1;</code>
             *
             * @return The bytes for commentFrom.
             */
            @java.lang.Override
            public com.google.protobuf.ByteString
            getCommentFromBytes() {
                java.lang.Object ref = commentFrom_;
                if (ref instanceof java.lang.String) {
                    com.google.protobuf.ByteString b =
                            com.google.protobuf.ByteString.copyFromUtf8(
                                    (java.lang.String) ref);
                    commentFrom_ = b;
                    return b;
                } else {
                    return (com.google.protobuf.ByteString) ref;
                }
            }

            public static final int COMMENT_FIELD_NUMBER = 2;
            private volatile java.lang.Object comment_;

            /**
             * <code>string comment = 2;</code>
             *
             * @return The comment.
             */
            @java.lang.Override
            public java.lang.String getComment() {
                java.lang.Object ref = comment_;
                if (ref instanceof java.lang.String) {
                    return (java.lang.String) ref;
                } else {
                    com.google.protobuf.ByteString bs =
                            (com.google.protobuf.ByteString) ref;
                    java.lang.String s = bs.toStringUtf8();
                    comment_ = s;
                    return s;
                }
            }

            /**
             * <code>string comment = 2;</code>
             *
             * @return The bytes for comment.
             */
            @java.lang.Override
            public com.google.protobuf.ByteString
            getCommentBytes() {
                java.lang.Object ref = comment_;
                if (ref instanceof java.lang.String) {
                    com.google.protobuf.ByteString b =
                            com.google.protobuf.ByteString.copyFromUtf8(
                                    (java.lang.String) ref);
                    comment_ = b;
                    return b;
                } else {
                    return (com.google.protobuf.ByteString) ref;
                }
            }

            public static final int COMMENTTIME_FIELD_NUMBER = 3;
            private com.google.protobuf.Timestamp commentTime_;

            /**
             * <code>.google.protobuf.Timestamp commentTime = 3;</code>
             *
             * @return Whether the commentTime field is set.
             */
            @java.lang.Override
            public boolean hasCommentTime() {
                return commentTime_ != null;
            }

            /**
             * <code>.google.protobuf.Timestamp commentTime = 3;</code>
             *
             * @return The commentTime.
             */
            @java.lang.Override
            public com.google.protobuf.Timestamp getCommentTime() {
                return commentTime_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : commentTime_;
            }

            /**
             * <code>.google.protobuf.Timestamp commentTime = 3;</code>
             */
            @java.lang.Override
            public com.google.protobuf.TimestampOrBuilder getCommentTimeOrBuilder() {
                return getCommentTime();
            }

            private byte memoizedIsInitialized = -1;

            @java.lang.Override
            public final boolean isInitialized() {
                byte isInitialized = memoizedIsInitialized;
                if (isInitialized == 1) return true;
                if (isInitialized == 0) return false;

                memoizedIsInitialized = 1;
                return true;
            }

            @java.lang.Override
            public void writeTo(com.google.protobuf.CodedOutputStream output)
                    throws java.io.IOException {
                if (!getCommentFromBytes().isEmpty()) {
                    com.google.protobuf.GeneratedMessageV3.writeString(output, 1, commentFrom_);
                }
                if (!getCommentBytes().isEmpty()) {
                    com.google.protobuf.GeneratedMessageV3.writeString(output, 2, comment_);
                }
                if (commentTime_ != null) {
                    output.writeMessage(3, getCommentTime());
                }
                unknownFields.writeTo(output);
            }

            @java.lang.Override
            public int getSerializedSize() {
                int size = memoizedSize;
                if (size != -1) return size;

                size = 0;
                if (!getCommentFromBytes().isEmpty()) {
                    size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, commentFrom_);
                }
                if (!getCommentBytes().isEmpty()) {
                    size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, comment_);
                }
                if (commentTime_ != null) {
                    size += com.google.protobuf.CodedOutputStream
                            .computeMessageSize(3, getCommentTime());
                }
                size += unknownFields.getSerializedSize();
                memoizedSize = size;
                return size;
            }

            @java.lang.Override
            public boolean equals(final java.lang.Object obj) {
                if (obj == this) {
                    return true;
                }
                if (!(obj instanceof RamensProto.Ramens.RamenComments)) {
                    return super.equals(obj);
                }
                RamensProto.Ramens.RamenComments other = (RamensProto.Ramens.RamenComments) obj;

                if (!getCommentFrom()
                        .equals(other.getCommentFrom())) return false;
                if (!getComment()
                        .equals(other.getComment())) return false;
                if (hasCommentTime() != other.hasCommentTime()) return false;
                if (hasCommentTime()) {
                    if (!getCommentTime()
                            .equals(other.getCommentTime())) return false;
                }
                if (!unknownFields.equals(other.unknownFields)) return false;
                return true;
            }

            @java.lang.Override
            public int hashCode() {
                if (memoizedHashCode != 0) {
                    return memoizedHashCode;
                }
                int hash = 41;
                hash = (19 * hash) + getDescriptor().hashCode();
                hash = (37 * hash) + COMMENTFROM_FIELD_NUMBER;
                hash = (53 * hash) + getCommentFrom().hashCode();
                hash = (37 * hash) + COMMENT_FIELD_NUMBER;
                hash = (53 * hash) + getComment().hashCode();
                if (hasCommentTime()) {
                    hash = (37 * hash) + COMMENTTIME_FIELD_NUMBER;
                    hash = (53 * hash) + getCommentTime().hashCode();
                }
                hash = (29 * hash) + unknownFields.hashCode();
                memoizedHashCode = hash;
                return hash;
            }

            public static RamensProto.Ramens.RamenComments parseFrom(
                    java.nio.ByteBuffer data)
                    throws com.google.protobuf.InvalidProtocolBufferException {
                return PARSER.parseFrom(data);
            }

            public static RamensProto.Ramens.RamenComments parseFrom(
                    java.nio.ByteBuffer data,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws com.google.protobuf.InvalidProtocolBufferException {
                return PARSER.parseFrom(data, extensionRegistry);
            }

            public static RamensProto.Ramens.RamenComments parseFrom(
                    com.google.protobuf.ByteString data)
                    throws com.google.protobuf.InvalidProtocolBufferException {
                return PARSER.parseFrom(data);
            }

            public static RamensProto.Ramens.RamenComments parseFrom(
                    com.google.protobuf.ByteString data,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws com.google.protobuf.InvalidProtocolBufferException {
                return PARSER.parseFrom(data, extensionRegistry);
            }

            public static RamensProto.Ramens.RamenComments parseFrom(byte[] data)
                    throws com.google.protobuf.InvalidProtocolBufferException {
                return PARSER.parseFrom(data);
            }

            public static RamensProto.Ramens.RamenComments parseFrom(
                    byte[] data,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws com.google.protobuf.InvalidProtocolBufferException {
                return PARSER.parseFrom(data, extensionRegistry);
            }

            public static RamensProto.Ramens.RamenComments parseFrom(java.io.InputStream input)
                    throws java.io.IOException {
                return com.google.protobuf.GeneratedMessageV3
                        .parseWithIOException(PARSER, input);
            }

            public static RamensProto.Ramens.RamenComments parseFrom(
                    java.io.InputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws java.io.IOException {
                return com.google.protobuf.GeneratedMessageV3
                        .parseWithIOException(PARSER, input, extensionRegistry);
            }

            public static RamensProto.Ramens.RamenComments parseDelimitedFrom(java.io.InputStream input)
                    throws java.io.IOException {
                return com.google.protobuf.GeneratedMessageV3
                        .parseDelimitedWithIOException(PARSER, input);
            }

            public static RamensProto.Ramens.RamenComments parseDelimitedFrom(
                    java.io.InputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws java.io.IOException {
                return com.google.protobuf.GeneratedMessageV3
                        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
            }

            public static RamensProto.Ramens.RamenComments parseFrom(
                    com.google.protobuf.CodedInputStream input)
                    throws java.io.IOException {
                return com.google.protobuf.GeneratedMessageV3
                        .parseWithIOException(PARSER, input);
            }

            public static RamensProto.Ramens.RamenComments parseFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws java.io.IOException {
                return com.google.protobuf.GeneratedMessageV3
                        .parseWithIOException(PARSER, input, extensionRegistry);
            }

            @java.lang.Override
            public Builder newBuilderForType() {
                return newBuilder();
            }

            public static Builder newBuilder() {
                return DEFAULT_INSTANCE.toBuilder();
            }

            public static Builder newBuilder(RamensProto.Ramens.RamenComments prototype) {
                return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
            }

            @java.lang.Override
            public Builder toBuilder() {
                return this == DEFAULT_INSTANCE
                        ? new Builder() : new Builder().mergeFrom(this);
            }

            @java.lang.Override
            protected Builder newBuilderForType(
                    com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
                Builder builder = new Builder(parent);
                return builder;
            }

            /**
             * Protobuf type {@code Ramens.RamenComments}
             */
            public static final class Builder extends
                    com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
                    // @@protoc_insertion_point(builder_implements:Ramens.RamenComments)
                    RamensProto.Ramens.RamenCommentsOrBuilder {
                public static final com.google.protobuf.Descriptors.Descriptor
                getDescriptor() {
                    return RamensProto.internal_static_Ramens_RamenComments_descriptor;
                }

                @java.lang.Override
                protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
                internalGetFieldAccessorTable() {
                    return RamensProto.internal_static_Ramens_RamenComments_fieldAccessorTable
                            .ensureFieldAccessorsInitialized(
                                    RamensProto.Ramens.RamenComments.class, RamensProto.Ramens.RamenComments.Builder.class);
                }

                // Construct using RamensProto.Ramens.RamenComments.newBuilder()
                private Builder() {
                    maybeForceBuilderInitialization();
                }

                private Builder(
                        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
                    super(parent);
                    maybeForceBuilderInitialization();
                }

                private void maybeForceBuilderInitialization() {
                    if (com.google.protobuf.GeneratedMessageV3
                            .alwaysUseFieldBuilders) {
                    }
                }

                @java.lang.Override
                public Builder clear() {
                    super.clear();
                    commentFrom_ = "";

                    comment_ = "";

                    if (commentTimeBuilder_ == null) {
                        commentTime_ = null;
                    } else {
                        commentTime_ = null;
                        commentTimeBuilder_ = null;
                    }
                    return this;
                }

                @java.lang.Override
                public com.google.protobuf.Descriptors.Descriptor
                getDescriptorForType() {
                    return RamensProto.internal_static_Ramens_RamenComments_descriptor;
                }

                @java.lang.Override
                public RamensProto.Ramens.RamenComments getDefaultInstanceForType() {
                    return RamensProto.Ramens.RamenComments.getDefaultInstance();
                }

                @java.lang.Override
                public RamensProto.Ramens.RamenComments build() {
                    RamensProto.Ramens.RamenComments result = buildPartial();
                    if (!result.isInitialized()) {
                        throw newUninitializedMessageException(result);
                    }
                    return result;
                }

                @java.lang.Override
                public RamensProto.Ramens.RamenComments buildPartial() {
                    RamensProto.Ramens.RamenComments result = new RamensProto.Ramens.RamenComments(this);
                    result.commentFrom_ = commentFrom_;
                    result.comment_ = comment_;
                    if (commentTimeBuilder_ == null) {
                        result.commentTime_ = commentTime_;
                    } else {
                        result.commentTime_ = commentTimeBuilder_.build();
                    }
                    onBuilt();
                    return result;
                }

                @java.lang.Override
                public Builder clone() {
                    return super.clone();
                }

                @java.lang.Override
                public Builder setField(
                        com.google.protobuf.Descriptors.FieldDescriptor field,
                        java.lang.Object value) {
                    return super.setField(field, value);
                }

                @java.lang.Override
                public Builder clearField(
                        com.google.protobuf.Descriptors.FieldDescriptor field) {
                    return super.clearField(field);
                }

                @java.lang.Override
                public Builder clearOneof(
                        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
                    return super.clearOneof(oneof);
                }

                @java.lang.Override
                public Builder setRepeatedField(
                        com.google.protobuf.Descriptors.FieldDescriptor field,
                        int index, java.lang.Object value) {
                    return super.setRepeatedField(field, index, value);
                }

                @java.lang.Override
                public Builder addRepeatedField(
                        com.google.protobuf.Descriptors.FieldDescriptor field,
                        java.lang.Object value) {
                    return super.addRepeatedField(field, value);
                }

                @java.lang.Override
                public Builder mergeFrom(com.google.protobuf.Message other) {
                    if (other instanceof RamensProto.Ramens.RamenComments) {
                        return mergeFrom((RamensProto.Ramens.RamenComments) other);
                    } else {
                        super.mergeFrom(other);
                        return this;
                    }
                }

                public Builder mergeFrom(RamensProto.Ramens.RamenComments other) {
                    if (other == RamensProto.Ramens.RamenComments.getDefaultInstance()) return this;
                    if (!other.getCommentFrom().isEmpty()) {
                        commentFrom_ = other.commentFrom_;
                        onChanged();
                    }
                    if (!other.getComment().isEmpty()) {
                        comment_ = other.comment_;
                        onChanged();
                    }
                    if (other.hasCommentTime()) {
                        mergeCommentTime(other.getCommentTime());
                    }
                    this.mergeUnknownFields(other.unknownFields);
                    onChanged();
                    return this;
                }

                @java.lang.Override
                public final boolean isInitialized() {
                    return true;
                }

                @java.lang.Override
                public Builder mergeFrom(
                        com.google.protobuf.CodedInputStream input,
                        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                        throws java.io.IOException {
                    RamensProto.Ramens.RamenComments parsedMessage = null;
                    try {
                        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
                    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                        parsedMessage = (RamensProto.Ramens.RamenComments) e.getUnfinishedMessage();
                        throw e.unwrapIOException();
                    } finally {
                        if (parsedMessage != null) {
                            mergeFrom(parsedMessage);
                        }
                    }
                    return this;
                }

                private java.lang.Object commentFrom_ = "";

                /**
                 * <code>string commentFrom = 1;</code>
                 *
                 * @return The commentFrom.
                 */
                public java.lang.String getCommentFrom() {
                    java.lang.Object ref = commentFrom_;
                    if (!(ref instanceof java.lang.String)) {
                        com.google.protobuf.ByteString bs =
                                (com.google.protobuf.ByteString) ref;
                        java.lang.String s = bs.toStringUtf8();
                        commentFrom_ = s;
                        return s;
                    } else {
                        return (java.lang.String) ref;
                    }
                }

                /**
                 * <code>string commentFrom = 1;</code>
                 *
                 * @return The bytes for commentFrom.
                 */
                public com.google.protobuf.ByteString
                getCommentFromBytes() {
                    java.lang.Object ref = commentFrom_;
                    if (ref instanceof String) {
                        com.google.protobuf.ByteString b =
                                com.google.protobuf.ByteString.copyFromUtf8(
                                        (java.lang.String) ref);
                        commentFrom_ = b;
                        return b;
                    } else {
                        return (com.google.protobuf.ByteString) ref;
                    }
                }

                /**
                 * <code>string commentFrom = 1;</code>
                 *
                 * @param value The commentFrom to set.
                 * @return This builder for chaining.
                 */
                public Builder setCommentFrom(
                        java.lang.String value) {
                    if (value == null) {
                        throw new NullPointerException();
                    }

                    commentFrom_ = value;
                    onChanged();
                    return this;
                }

                /**
                 * <code>string commentFrom = 1;</code>
                 *
                 * @return This builder for chaining.
                 */
                public Builder clearCommentFrom() {

                    commentFrom_ = getDefaultInstance().getCommentFrom();
                    onChanged();
                    return this;
                }

                /**
                 * <code>string commentFrom = 1;</code>
                 *
                 * @param value The bytes for commentFrom to set.
                 * @return This builder for chaining.
                 */
                public Builder setCommentFromBytes(
                        com.google.protobuf.ByteString value) {
                    if (value == null) {
                        throw new NullPointerException();
                    }
                    checkByteStringIsUtf8(value);

                    commentFrom_ = value;
                    onChanged();
                    return this;
                }

                private java.lang.Object comment_ = "";

                /**
                 * <code>string comment = 2;</code>
                 *
                 * @return The comment.
                 */
                public java.lang.String getComment() {
                    java.lang.Object ref = comment_;
                    if (!(ref instanceof java.lang.String)) {
                        com.google.protobuf.ByteString bs =
                                (com.google.protobuf.ByteString) ref;
                        java.lang.String s = bs.toStringUtf8();
                        comment_ = s;
                        return s;
                    } else {
                        return (java.lang.String) ref;
                    }
                }

                /**
                 * <code>string comment = 2;</code>
                 *
                 * @return The bytes for comment.
                 */
                public com.google.protobuf.ByteString
                getCommentBytes() {
                    java.lang.Object ref = comment_;
                    if (ref instanceof String) {
                        com.google.protobuf.ByteString b =
                                com.google.protobuf.ByteString.copyFromUtf8(
                                        (java.lang.String) ref);
                        comment_ = b;
                        return b;
                    } else {
                        return (com.google.protobuf.ByteString) ref;
                    }
                }

                /**
                 * <code>string comment = 2;</code>
                 *
                 * @param value The comment to set.
                 * @return This builder for chaining.
                 */
                public Builder setComment(
                        java.lang.String value) {
                    if (value == null) {
                        throw new NullPointerException();
                    }

                    comment_ = value;
                    onChanged();
                    return this;
                }

                /**
                 * <code>string comment = 2;</code>
                 *
                 * @return This builder for chaining.
                 */
                public Builder clearComment() {

                    comment_ = getDefaultInstance().getComment();
                    onChanged();
                    return this;
                }

                /**
                 * <code>string comment = 2;</code>
                 *
                 * @param value The bytes for comment to set.
                 * @return This builder for chaining.
                 */
                public Builder setCommentBytes(
                        com.google.protobuf.ByteString value) {
                    if (value == null) {
                        throw new NullPointerException();
                    }
                    checkByteStringIsUtf8(value);

                    comment_ = value;
                    onChanged();
                    return this;
                }

                private com.google.protobuf.Timestamp commentTime_;
                private com.google.protobuf.SingleFieldBuilderV3<
                        com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> commentTimeBuilder_;

                /**
                 * <code>.google.protobuf.Timestamp commentTime = 3;</code>
                 *
                 * @return Whether the commentTime field is set.
                 */
                public boolean hasCommentTime() {
                    return commentTimeBuilder_ != null || commentTime_ != null;
                }

                /**
                 * <code>.google.protobuf.Timestamp commentTime = 3;</code>
                 *
                 * @return The commentTime.
                 */
                public com.google.protobuf.Timestamp getCommentTime() {
                    if (commentTimeBuilder_ == null) {
                        return commentTime_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : commentTime_;
                    } else {
                        return commentTimeBuilder_.getMessage();
                    }
                }

                /**
                 * <code>.google.protobuf.Timestamp commentTime = 3;</code>
                 */
                public Builder setCommentTime(com.google.protobuf.Timestamp value) {
                    if (commentTimeBuilder_ == null) {
                        if (value == null) {
                            throw new NullPointerException();
                        }
                        commentTime_ = value;
                        onChanged();
                    } else {
                        commentTimeBuilder_.setMessage(value);
                    }

                    return this;
                }

                /**
                 * <code>.google.protobuf.Timestamp commentTime = 3;</code>
                 */
                public Builder setCommentTime(
                        com.google.protobuf.Timestamp.Builder builderForValue) {
                    if (commentTimeBuilder_ == null) {
                        commentTime_ = builderForValue.build();
                        onChanged();
                    } else {
                        commentTimeBuilder_.setMessage(builderForValue.build());
                    }

                    return this;
                }

                /**
                 * <code>.google.protobuf.Timestamp commentTime = 3;</code>
                 */
                public Builder mergeCommentTime(com.google.protobuf.Timestamp value) {
                    if (commentTimeBuilder_ == null) {
                        if (commentTime_ != null) {
                            commentTime_ =
                                    com.google.protobuf.Timestamp.newBuilder(commentTime_).mergeFrom(value).buildPartial();
                        } else {
                            commentTime_ = value;
                        }
                        onChanged();
                    } else {
                        commentTimeBuilder_.mergeFrom(value);
                    }

                    return this;
                }

                /**
                 * <code>.google.protobuf.Timestamp commentTime = 3;</code>
                 */
                public Builder clearCommentTime() {
                    if (commentTimeBuilder_ == null) {
                        commentTime_ = null;
                        onChanged();
                    } else {
                        commentTime_ = null;
                        commentTimeBuilder_ = null;
                    }

                    return this;
                }

                /**
                 * <code>.google.protobuf.Timestamp commentTime = 3;</code>
                 */
                public com.google.protobuf.Timestamp.Builder getCommentTimeBuilder() {

                    onChanged();
                    return getCommentTimeFieldBuilder().getBuilder();
                }

                /**
                 * <code>.google.protobuf.Timestamp commentTime = 3;</code>
                 */
                public com.google.protobuf.TimestampOrBuilder getCommentTimeOrBuilder() {
                    if (commentTimeBuilder_ != null) {
                        return commentTimeBuilder_.getMessageOrBuilder();
                    } else {
                        return commentTime_ == null ?
                                com.google.protobuf.Timestamp.getDefaultInstance() : commentTime_;
                    }
                }

                /**
                 * <code>.google.protobuf.Timestamp commentTime = 3;</code>
                 */
                private com.google.protobuf.SingleFieldBuilderV3<
                        com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder>
                getCommentTimeFieldBuilder() {
                    if (commentTimeBuilder_ == null) {
                        commentTimeBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
                                com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder>(
                                getCommentTime(),
                                getParentForChildren(),
                                isClean());
                        commentTime_ = null;
                    }
                    return commentTimeBuilder_;
                }

                @java.lang.Override
                public final Builder setUnknownFields(
                        final com.google.protobuf.UnknownFieldSet unknownFields) {
                    return super.setUnknownFields(unknownFields);
                }

                @java.lang.Override
                public final Builder mergeUnknownFields(
                        final com.google.protobuf.UnknownFieldSet unknownFields) {
                    return super.mergeUnknownFields(unknownFields);
                }


                // @@protoc_insertion_point(builder_scope:Ramens.RamenComments)
            }

            // @@protoc_insertion_point(class_scope:Ramens.RamenComments)
            private static final RamensProto.Ramens.RamenComments DEFAULT_INSTANCE;

            static {
                DEFAULT_INSTANCE = new RamensProto.Ramens.RamenComments();
            }

            public static RamensProto.Ramens.RamenComments getDefaultInstance() {
                return DEFAULT_INSTANCE;
            }

            private static final com.google.protobuf.Parser<RamenComments>
                    PARSER = new com.google.protobuf.AbstractParser<RamenComments>() {
                @java.lang.Override
                public RamenComments parsePartialFrom(
                        com.google.protobuf.CodedInputStream input,
                        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                        throws com.google.protobuf.InvalidProtocolBufferException {
                    return new RamenComments(input, extensionRegistry);
                }
            };

            public static com.google.protobuf.Parser<RamenComments> parser() {
                return PARSER;
            }

            @java.lang.Override
            public com.google.protobuf.Parser<RamenComments> getParserForType() {
                return PARSER;
            }

            @java.lang.Override
            public RamensProto.Ramens.RamenComments getDefaultInstanceForType() {
                return DEFAULT_INSTANCE;
            }

        }

        public static final int RAMENNAME_FIELD_NUMBER = 1;
        private volatile java.lang.Object ramenName_;

        /**
         * <code>string ramenName = 1;</code>
         *
         * @return The ramenName.
         */
        @java.lang.Override
        public java.lang.String getRamenName() {
            java.lang.Object ref = ramenName_;
            if (ref instanceof java.lang.String) {
                return (java.lang.String) ref;
            } else {
                com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                java.lang.String s = bs.toStringUtf8();
                ramenName_ = s;
                return s;
            }
        }

        /**
         * <code>string ramenName = 1;</code>
         *
         * @return The bytes for ramenName.
         */
        @java.lang.Override
        public com.google.protobuf.ByteString
        getRamenNameBytes() {
            java.lang.Object ref = ramenName_;
            if (ref instanceof java.lang.String) {
                com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8(
                                (java.lang.String) ref);
                ramenName_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        public static final int INRRATE_FIELD_NUMBER = 2;
        private double inrRate_;

        /**
         * <code>double inrRate = 2;</code>
         *
         * @return The inrRate.
         */
        @java.lang.Override
        public double getInrRate() {
            return inrRate_;
        }

        public static final int COMMENTS_FIELD_NUMBER = 3;
        private java.util.List<RamensProto.Ramens.RamenComments> comments_;

        /**
         * <code>repeated .Ramens.RamenComments comments = 3;</code>
         */
        @java.lang.Override
        public java.util.List<RamensProto.Ramens.RamenComments> getCommentsList() {
            return comments_;
        }

        /**
         * <code>repeated .Ramens.RamenComments comments = 3;</code>
         */
        @java.lang.Override
        public java.util.List<? extends RamensProto.Ramens.RamenCommentsOrBuilder>
        getCommentsOrBuilderList() {
            return comments_;
        }

        /**
         * <code>repeated .Ramens.RamenComments comments = 3;</code>
         */
        @java.lang.Override
        public int getCommentsCount() {
            return comments_.size();
        }

        /**
         * <code>repeated .Ramens.RamenComments comments = 3;</code>
         */
        @java.lang.Override
        public RamensProto.Ramens.RamenComments getComments(int index) {
            return comments_.get(index);
        }

        /**
         * <code>repeated .Ramens.RamenComments comments = 3;</code>
         */
        @java.lang.Override
        public RamensProto.Ramens.RamenCommentsOrBuilder getCommentsOrBuilder(
                int index) {
            return comments_.get(index);
        }

        private byte memoizedIsInitialized = -1;

        @java.lang.Override
        public final boolean isInitialized() {
            byte isInitialized = memoizedIsInitialized;
            if (isInitialized == 1) return true;
            if (isInitialized == 0) return false;

            memoizedIsInitialized = 1;
            return true;
        }

        @java.lang.Override
        public void writeTo(com.google.protobuf.CodedOutputStream output)
                throws java.io.IOException {
            if (!getRamenNameBytes().isEmpty()) {
                com.google.protobuf.GeneratedMessageV3.writeString(output, 1, ramenName_);
            }
            if (inrRate_ != 0D) {
                output.writeDouble(2, inrRate_);
            }
            for (int i = 0; i < comments_.size(); i++) {
                output.writeMessage(3, comments_.get(i));
            }
            unknownFields.writeTo(output);
        }

        @java.lang.Override
        public int getSerializedSize() {
            int size = memoizedSize;
            if (size != -1) return size;

            size = 0;
            if (!getRamenNameBytes().isEmpty()) {
                size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, ramenName_);
            }
            if (inrRate_ != 0D) {
                size += com.google.protobuf.CodedOutputStream
                        .computeDoubleSize(2, inrRate_);
            }
            for (int i = 0; i < comments_.size(); i++) {
                size += com.google.protobuf.CodedOutputStream
                        .computeMessageSize(3, comments_.get(i));
            }
            size += unknownFields.getSerializedSize();
            memoizedSize = size;
            return size;
        }

        @java.lang.Override
        public boolean equals(final java.lang.Object obj) {
            if (obj == this) {
                return true;
            }
            if (!(obj instanceof RamensProto.Ramens)) {
                return super.equals(obj);
            }
            RamensProto.Ramens other = (RamensProto.Ramens) obj;

            if (!getRamenName()
                    .equals(other.getRamenName())) return false;
            if (java.lang.Double.doubleToLongBits(getInrRate())
                    != java.lang.Double.doubleToLongBits(
                    other.getInrRate())) return false;
            if (!getCommentsList()
                    .equals(other.getCommentsList())) return false;
            if (!unknownFields.equals(other.unknownFields)) return false;
            return true;
        }

        @java.lang.Override
        public int hashCode() {
            if (memoizedHashCode != 0) {
                return memoizedHashCode;
            }
            int hash = 41;
            hash = (19 * hash) + getDescriptor().hashCode();
            hash = (37 * hash) + RAMENNAME_FIELD_NUMBER;
            hash = (53 * hash) + getRamenName().hashCode();
            hash = (37 * hash) + INRRATE_FIELD_NUMBER;
            hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
                    java.lang.Double.doubleToLongBits(getInrRate()));
            if (getCommentsCount() > 0) {
                hash = (37 * hash) + COMMENTS_FIELD_NUMBER;
                hash = (53 * hash) + getCommentsList().hashCode();
            }
            hash = (29 * hash) + unknownFields.hashCode();
            memoizedHashCode = hash;
            return hash;
        }

        public static RamensProto.Ramens parseFrom(
                java.nio.ByteBuffer data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static RamensProto.Ramens parseFrom(
                java.nio.ByteBuffer data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static RamensProto.Ramens parseFrom(
                com.google.protobuf.ByteString data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static RamensProto.Ramens parseFrom(
                com.google.protobuf.ByteString data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static RamensProto.Ramens parseFrom(byte[] data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static RamensProto.Ramens parseFrom(
                byte[] data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static RamensProto.Ramens parseFrom(java.io.InputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input);
        }

        public static RamensProto.Ramens parseFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input, extensionRegistry);
        }

        public static RamensProto.Ramens parseDelimitedFrom(java.io.InputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseDelimitedWithIOException(PARSER, input);
        }

        public static RamensProto.Ramens parseDelimitedFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
        }

        public static RamensProto.Ramens parseFrom(
                com.google.protobuf.CodedInputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input);
        }

        public static RamensProto.Ramens parseFrom(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input, extensionRegistry);
        }

        @java.lang.Override
        public Builder newBuilderForType() {
            return newBuilder();
        }

        public static Builder newBuilder() {
            return DEFAULT_INSTANCE.toBuilder();
        }

        public static Builder newBuilder(RamensProto.Ramens prototype) {
            return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
        }

        @java.lang.Override
        public Builder toBuilder() {
            return this == DEFAULT_INSTANCE
                    ? new Builder() : new Builder().mergeFrom(this);
        }

        @java.lang.Override
        protected Builder newBuilderForType(
                com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
            Builder builder = new Builder(parent);
            return builder;
        }

        /**
         * Protobuf type {@code Ramens}
         */
        public static final class Builder extends
                com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
                // @@protoc_insertion_point(builder_implements:Ramens)
                RamensProto.RamensOrBuilder {
            public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
                return RamensProto.internal_static_Ramens_descriptor;
            }

            @java.lang.Override
            protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internalGetFieldAccessorTable() {
                return RamensProto.internal_static_Ramens_fieldAccessorTable
                        .ensureFieldAccessorsInitialized(
                                RamensProto.Ramens.class, RamensProto.Ramens.Builder.class);
            }

            // Construct using RamensProto.Ramens.newBuilder()
            private Builder() {
                maybeForceBuilderInitialization();
            }

            private Builder(
                    com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
                super(parent);
                maybeForceBuilderInitialization();
            }

            private void maybeForceBuilderInitialization() {
                if (com.google.protobuf.GeneratedMessageV3
                        .alwaysUseFieldBuilders) {
                    getCommentsFieldBuilder();
                }
            }

            @java.lang.Override
            public Builder clear() {
                super.clear();
                ramenName_ = "";

                inrRate_ = 0D;

                if (commentsBuilder_ == null) {
                    comments_ = java.util.Collections.emptyList();
                    bitField0_ = (bitField0_ & ~0x00000001);
                } else {
                    commentsBuilder_.clear();
                }
                return this;
            }

            @java.lang.Override
            public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
                return RamensProto.internal_static_Ramens_descriptor;
            }

            @java.lang.Override
            public RamensProto.Ramens getDefaultInstanceForType() {
                return RamensProto.Ramens.getDefaultInstance();
            }

            @java.lang.Override
            public RamensProto.Ramens build() {
                RamensProto.Ramens result = buildPartial();
                if (!result.isInitialized()) {
                    throw newUninitializedMessageException(result);
                }
                return result;
            }

            @java.lang.Override
            public RamensProto.Ramens buildPartial() {
                RamensProto.Ramens result = new RamensProto.Ramens(this);
                int from_bitField0_ = bitField0_;
                result.ramenName_ = ramenName_;
                result.inrRate_ = inrRate_;
                if (commentsBuilder_ == null) {
                    if (((bitField0_ & 0x00000001) != 0)) {
                        comments_ = java.util.Collections.unmodifiableList(comments_);
                        bitField0_ = (bitField0_ & ~0x00000001);
                    }
                    result.comments_ = comments_;
                } else {
                    result.comments_ = commentsBuilder_.build();
                }
                onBuilt();
                return result;
            }

            @java.lang.Override
            public Builder clone() {
                return super.clone();
            }

            @java.lang.Override
            public Builder setField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    java.lang.Object value) {
                return super.setField(field, value);
            }

            @java.lang.Override
            public Builder clearField(
                    com.google.protobuf.Descriptors.FieldDescriptor field) {
                return super.clearField(field);
            }

            @java.lang.Override
            public Builder clearOneof(
                    com.google.protobuf.Descriptors.OneofDescriptor oneof) {
                return super.clearOneof(oneof);
            }

            @java.lang.Override
            public Builder setRepeatedField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    int index, java.lang.Object value) {
                return super.setRepeatedField(field, index, value);
            }

            @java.lang.Override
            public Builder addRepeatedField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    java.lang.Object value) {
                return super.addRepeatedField(field, value);
            }

            @java.lang.Override
            public Builder mergeFrom(com.google.protobuf.Message other) {
                if (other instanceof RamensProto.Ramens) {
                    return mergeFrom((RamensProto.Ramens) other);
                } else {
                    super.mergeFrom(other);
                    return this;
                }
            }

            public Builder mergeFrom(RamensProto.Ramens other) {
                if (other == RamensProto.Ramens.getDefaultInstance()) return this;
                if (!other.getRamenName().isEmpty()) {
                    ramenName_ = other.ramenName_;
                    onChanged();
                }
                if (other.getInrRate() != 0D) {
                    setInrRate(other.getInrRate());
                }
                if (commentsBuilder_ == null) {
                    if (!other.comments_.isEmpty()) {
                        if (comments_.isEmpty()) {
                            comments_ = other.comments_;
                            bitField0_ = (bitField0_ & ~0x00000001);
                        } else {
                            ensureCommentsIsMutable();
                            comments_.addAll(other.comments_);
                        }
                        onChanged();
                    }
                } else {
                    if (!other.comments_.isEmpty()) {
                        if (commentsBuilder_.isEmpty()) {
                            commentsBuilder_.dispose();
                            commentsBuilder_ = null;
                            comments_ = other.comments_;
                            bitField0_ = (bitField0_ & ~0x00000001);
                            commentsBuilder_ =
                                    com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                                            getCommentsFieldBuilder() : null;
                        } else {
                            commentsBuilder_.addAllMessages(other.comments_);
                        }
                    }
                }
                this.mergeUnknownFields(other.unknownFields);
                onChanged();
                return this;
            }

            @java.lang.Override
            public final boolean isInitialized() {
                return true;
            }

            @java.lang.Override
            public Builder mergeFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws java.io.IOException {
                RamensProto.Ramens parsedMessage = null;
                try {
                    parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
                } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                    parsedMessage = (RamensProto.Ramens) e.getUnfinishedMessage();
                    throw e.unwrapIOException();
                } finally {
                    if (parsedMessage != null) {
                        mergeFrom(parsedMessage);
                    }
                }
                return this;
            }

            private int bitField0_;

            private java.lang.Object ramenName_ = "";

            /**
             * <code>string ramenName = 1;</code>
             *
             * @return The ramenName.
             */
            public java.lang.String getRamenName() {
                java.lang.Object ref = ramenName_;
                if (!(ref instanceof java.lang.String)) {
                    com.google.protobuf.ByteString bs =
                            (com.google.protobuf.ByteString) ref;
                    java.lang.String s = bs.toStringUtf8();
                    ramenName_ = s;
                    return s;
                } else {
                    return (java.lang.String) ref;
                }
            }

            /**
             * <code>string ramenName = 1;</code>
             *
             * @return The bytes for ramenName.
             */
            public com.google.protobuf.ByteString
            getRamenNameBytes() {
                java.lang.Object ref = ramenName_;
                if (ref instanceof String) {
                    com.google.protobuf.ByteString b =
                            com.google.protobuf.ByteString.copyFromUtf8(
                                    (java.lang.String) ref);
                    ramenName_ = b;
                    return b;
                } else {
                    return (com.google.protobuf.ByteString) ref;
                }
            }

            /**
             * <code>string ramenName = 1;</code>
             *
             * @param value The ramenName to set.
             * @return This builder for chaining.
             */
            public Builder setRamenName(
                    java.lang.String value) {
                if (value == null) {
                    throw new NullPointerException();
                }

                ramenName_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>string ramenName = 1;</code>
             *
             * @return This builder for chaining.
             */
            public Builder clearRamenName() {

                ramenName_ = getDefaultInstance().getRamenName();
                onChanged();
                return this;
            }

            /**
             * <code>string ramenName = 1;</code>
             *
             * @param value The bytes for ramenName to set.
             * @return This builder for chaining.
             */
            public Builder setRamenNameBytes(
                    com.google.protobuf.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                checkByteStringIsUtf8(value);

                ramenName_ = value;
                onChanged();
                return this;
            }

            private double inrRate_;

            /**
             * <code>double inrRate = 2;</code>
             *
             * @return The inrRate.
             */
            @java.lang.Override
            public double getInrRate() {
                return inrRate_;
            }

            /**
             * <code>double inrRate = 2;</code>
             *
             * @param value The inrRate to set.
             * @return This builder for chaining.
             */
            public Builder setInrRate(double value) {

                inrRate_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>double inrRate = 2;</code>
             *
             * @return This builder for chaining.
             */
            public Builder clearInrRate() {

                inrRate_ = 0D;
                onChanged();
                return this;
            }

            private java.util.List<RamensProto.Ramens.RamenComments> comments_ =
                    java.util.Collections.emptyList();

            private void ensureCommentsIsMutable() {
                if (!((bitField0_ & 0x00000001) != 0)) {
                    comments_ = new java.util.ArrayList<RamensProto.Ramens.RamenComments>(comments_);
                    bitField0_ |= 0x00000001;
                }
            }

            private com.google.protobuf.RepeatedFieldBuilderV3<
                    RamensProto.Ramens.RamenComments, RamensProto.Ramens.RamenComments.Builder, RamensProto.Ramens.RamenCommentsOrBuilder> commentsBuilder_;

            /**
             * <code>repeated .Ramens.RamenComments comments = 3;</code>
             */
            public java.util.List<RamensProto.Ramens.RamenComments> getCommentsList() {
                if (commentsBuilder_ == null) {
                    return java.util.Collections.unmodifiableList(comments_);
                } else {
                    return commentsBuilder_.getMessageList();
                }
            }

            /**
             * <code>repeated .Ramens.RamenComments comments = 3;</code>
             */
            public int getCommentsCount() {
                if (commentsBuilder_ == null) {
                    return comments_.size();
                } else {
                    return commentsBuilder_.getCount();
                }
            }

            /**
             * <code>repeated .Ramens.RamenComments comments = 3;</code>
             */
            public RamensProto.Ramens.RamenComments getComments(int index) {
                if (commentsBuilder_ == null) {
                    return comments_.get(index);
                } else {
                    return commentsBuilder_.getMessage(index);
                }
            }

            /**
             * <code>repeated .Ramens.RamenComments comments = 3;</code>
             */
            public Builder setComments(
                    int index, RamensProto.Ramens.RamenComments value) {
                if (commentsBuilder_ == null) {
                    if (value == null) {
                        throw new NullPointerException();
                    }
                    ensureCommentsIsMutable();
                    comments_.set(index, value);
                    onChanged();
                } else {
                    commentsBuilder_.setMessage(index, value);
                }
                return this;
            }

            /**
             * <code>repeated .Ramens.RamenComments comments = 3;</code>
             */
            public Builder setComments(
                    int index, RamensProto.Ramens.RamenComments.Builder builderForValue) {
                if (commentsBuilder_ == null) {
                    ensureCommentsIsMutable();
                    comments_.set(index, builderForValue.build());
                    onChanged();
                } else {
                    commentsBuilder_.setMessage(index, builderForValue.build());
                }
                return this;
            }

            /**
             * <code>repeated .Ramens.RamenComments comments = 3;</code>
             */
            public Builder addComments(RamensProto.Ramens.RamenComments value) {
                if (commentsBuilder_ == null) {
                    if (value == null) {
                        throw new NullPointerException();
                    }
                    ensureCommentsIsMutable();
                    comments_.add(value);
                    onChanged();
                } else {
                    commentsBuilder_.addMessage(value);
                }
                return this;
            }

            /**
             * <code>repeated .Ramens.RamenComments comments = 3;</code>
             */
            public Builder addComments(
                    int index, RamensProto.Ramens.RamenComments value) {
                if (commentsBuilder_ == null) {
                    if (value == null) {
                        throw new NullPointerException();
                    }
                    ensureCommentsIsMutable();
                    comments_.add(index, value);
                    onChanged();
                } else {
                    commentsBuilder_.addMessage(index, value);
                }
                return this;
            }

            /**
             * <code>repeated .Ramens.RamenComments comments = 3;</code>
             */
            public Builder addComments(
                    RamensProto.Ramens.RamenComments.Builder builderForValue) {
                if (commentsBuilder_ == null) {
                    ensureCommentsIsMutable();
                    comments_.add(builderForValue.build());
                    onChanged();
                } else {
                    commentsBuilder_.addMessage(builderForValue.build());
                }
                return this;
            }

            /**
             * <code>repeated .Ramens.RamenComments comments = 3;</code>
             */
            public Builder addComments(
                    int index, RamensProto.Ramens.RamenComments.Builder builderForValue) {
                if (commentsBuilder_ == null) {
                    ensureCommentsIsMutable();
                    comments_.add(index, builderForValue.build());
                    onChanged();
                } else {
                    commentsBuilder_.addMessage(index, builderForValue.build());
                }
                return this;
            }

            /**
             * <code>repeated .Ramens.RamenComments comments = 3;</code>
             */
            public Builder addAllComments(
                    java.lang.Iterable<? extends RamensProto.Ramens.RamenComments> values) {
                if (commentsBuilder_ == null) {
                    ensureCommentsIsMutable();
                    com.google.protobuf.AbstractMessageLite.Builder.addAll(
                            values, comments_);
                    onChanged();
                } else {
                    commentsBuilder_.addAllMessages(values);
                }
                return this;
            }

            /**
             * <code>repeated .Ramens.RamenComments comments = 3;</code>
             */
            public Builder clearComments() {
                if (commentsBuilder_ == null) {
                    comments_ = java.util.Collections.emptyList();
                    bitField0_ = (bitField0_ & ~0x00000001);
                    onChanged();
                } else {
                    commentsBuilder_.clear();
                }
                return this;
            }

            /**
             * <code>repeated .Ramens.RamenComments comments = 3;</code>
             */
            public Builder removeComments(int index) {
                if (commentsBuilder_ == null) {
                    ensureCommentsIsMutable();
                    comments_.remove(index);
                    onChanged();
                } else {
                    commentsBuilder_.remove(index);
                }
                return this;
            }

            /**
             * <code>repeated .Ramens.RamenComments comments = 3;</code>
             */
            public RamensProto.Ramens.RamenComments.Builder getCommentsBuilder(
                    int index) {
                return getCommentsFieldBuilder().getBuilder(index);
            }

            /**
             * <code>repeated .Ramens.RamenComments comments = 3;</code>
             */
            public RamensProto.Ramens.RamenCommentsOrBuilder getCommentsOrBuilder(
                    int index) {
                if (commentsBuilder_ == null) {
                    return comments_.get(index);
                } else {
                    return commentsBuilder_.getMessageOrBuilder(index);
                }
            }

            /**
             * <code>repeated .Ramens.RamenComments comments = 3;</code>
             */
            public java.util.List<? extends RamensProto.Ramens.RamenCommentsOrBuilder>
            getCommentsOrBuilderList() {
                if (commentsBuilder_ != null) {
                    return commentsBuilder_.getMessageOrBuilderList();
                } else {
                    return java.util.Collections.unmodifiableList(comments_);
                }
            }

            /**
             * <code>repeated .Ramens.RamenComments comments = 3;</code>
             */
            public RamensProto.Ramens.RamenComments.Builder addCommentsBuilder() {
                return getCommentsFieldBuilder().addBuilder(
                        RamensProto.Ramens.RamenComments.getDefaultInstance());
            }

            /**
             * <code>repeated .Ramens.RamenComments comments = 3;</code>
             */
            public RamensProto.Ramens.RamenComments.Builder addCommentsBuilder(
                    int index) {
                return getCommentsFieldBuilder().addBuilder(
                        index, RamensProto.Ramens.RamenComments.getDefaultInstance());
            }

            /**
             * <code>repeated .Ramens.RamenComments comments = 3;</code>
             */
            public java.util.List<RamensProto.Ramens.RamenComments.Builder>
            getCommentsBuilderList() {
                return getCommentsFieldBuilder().getBuilderList();
            }

            private com.google.protobuf.RepeatedFieldBuilderV3<
                    RamensProto.Ramens.RamenComments, RamensProto.Ramens.RamenComments.Builder, RamensProto.Ramens.RamenCommentsOrBuilder>
            getCommentsFieldBuilder() {
                if (commentsBuilder_ == null) {
                    commentsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
                            RamensProto.Ramens.RamenComments, RamensProto.Ramens.RamenComments.Builder, RamensProto.Ramens.RamenCommentsOrBuilder>(
                            comments_,
                            ((bitField0_ & 0x00000001) != 0),
                            getParentForChildren(),
                            isClean());
                    comments_ = null;
                }
                return commentsBuilder_;
            }

            @java.lang.Override
            public final Builder setUnknownFields(
                    final com.google.protobuf.UnknownFieldSet unknownFields) {
                return super.setUnknownFields(unknownFields);
            }

            @java.lang.Override
            public final Builder mergeUnknownFields(
                    final com.google.protobuf.UnknownFieldSet unknownFields) {
                return super.mergeUnknownFields(unknownFields);
            }


            // @@protoc_insertion_point(builder_scope:Ramens)
        }

        // @@protoc_insertion_point(class_scope:Ramens)
        private static final RamensProto.Ramens DEFAULT_INSTANCE;

        static {
            DEFAULT_INSTANCE = new RamensProto.Ramens();
        }

        public static RamensProto.Ramens getDefaultInstance() {
            return DEFAULT_INSTANCE;
        }

        private static final com.google.protobuf.Parser<Ramens>
                PARSER = new com.google.protobuf.AbstractParser<Ramens>() {
            @java.lang.Override
            public Ramens parsePartialFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws com.google.protobuf.InvalidProtocolBufferException {
                return new Ramens(input, extensionRegistry);
            }
        };

        public static com.google.protobuf.Parser<Ramens> parser() {
            return PARSER;
        }

        @java.lang.Override
        public com.google.protobuf.Parser<Ramens> getParserForType() {
            return PARSER;
        }

        @java.lang.Override
        public RamensProto.Ramens getDefaultInstanceForType() {
            return DEFAULT_INSTANCE;
        }

    }

    private static final com.google.protobuf.Descriptors.Descriptor
            internal_static_Ramens_descriptor;
    private static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internal_static_Ramens_fieldAccessorTable;
    private static final com.google.protobuf.Descriptors.Descriptor
            internal_static_Ramens_RamenComments_descriptor;
    private static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internal_static_Ramens_RamenComments_fieldAccessorTable;

    public static com.google.protobuf.Descriptors.FileDescriptor
    getDescriptor() {
        return descriptor;
    }

    private static com.google.protobuf.Descriptors.FileDescriptor
            descriptor;

    static {
        java.lang.String[] descriptorData = {
                "\n\021RamensProto.proto\032\037google/protobuf/tim" +
                        "estamp.proto\"\275\001\n\006Ramens\022\021\n\tramenName\030\001 \001" +
                        "(\t\022\017\n\007inrRate\030\002 \001(\001\022\'\n\010comments\030\003 \003(\0132\025." +
                        "Ramens.RamenComments\032f\n\rRamenComments\022\023\n" +
                        "\013commentFrom\030\001 \001(\t\022\017\n\007comment\030\002 \001(\t\022/\n\013c" +
                        "ommentTime\030\003 \001(\0132\032.google.protobuf.Times" +
                        "tampb\006proto3"
        };
        descriptor = com.google.protobuf.Descriptors.FileDescriptor
                .internalBuildGeneratedFileFrom(descriptorData,
                        new com.google.protobuf.Descriptors.FileDescriptor[]{
                                com.google.protobuf.TimestampProto.getDescriptor(),
                        });
        internal_static_Ramens_descriptor =
                getDescriptor().getMessageTypes().get(0);
        internal_static_Ramens_fieldAccessorTable = new
                com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
                internal_static_Ramens_descriptor,
                new java.lang.String[]{"RamenName", "InrRate", "Comments",});
        internal_static_Ramens_RamenComments_descriptor =
                internal_static_Ramens_descriptor.getNestedTypes().get(0);
        internal_static_Ramens_RamenComments_fieldAccessorTable = new
                com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
                internal_static_Ramens_RamenComments_descriptor,
                new java.lang.String[]{"CommentFrom", "Comment", "CommentTime",});
        com.google.protobuf.TimestampProto.getDescriptor();
    }

    // @@protoc_insertion_point(outer_class_scope)
}
